version: '3.8'
services:
  sender:
    build:
      context: ./test
    image: sender
    container_name: sender
    ports:
      - 5001:5000

  getter:
    build:
      context: ./test2
    image: getter
    container_name: getter
    ports:
      - 6001:6000
