version: '3.8'
services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - 9092:9092

  sender:
    build:
      context: ./test
    image: sender
    container_name: sender
    ports:
      - 6001:6001

  getter:
    build:
      context: ./test2
    image: getter
    container_name: getter
    ports:
      - 6000:6000
