version: '3.8'
services:
  sender:
    build:
      context: ./test
    image: sender
    container_name: senser
    ports:
      - 5000:5000

  getter:
    build:
      context: ./test2
    image: getter
    container_name: getter
    ports:
      - 6000:6000
